return {
	-- require("plugins.inlay-hints"),
	require("plugins.llama"),
	require("plugins.DoxygenToolkit"),
	require("plugins.auto-pairs"),
	require("plugins.cmake"),
	require("plugins.conform"),
	require("plugins.dap"),
	require("plugins.easy-align"),
	require("plugins.fugitive"),
	require("plugins.gruvbox"),
	require("plugins.lsp"),
	require("plugins.mason"),
	require("plugins.mini"),
	require("plugins.nvim-cmp"),
	require("plugins.nvim-comment"),
	require("plugins.nvim-ts-autotag"),
	require("plugins.oil"),
	require("plugins.telescope"),
	require("plugins.theme"),
	require("plugins.treesitter"),
	require("plugins.ufo"),
	require("plugins.undotree"),
	require("plugins.vim-easy-align"),
	require("plugins.vim-multiple-cursors"),
	require("plugins.vimtex"),
	require("plugins.vim-flog"),
}
